version: 2
jobs:
  build:
    working_directory: ~/WEB5A
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: WEB5A-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: WEB5A-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test -- --no-watch --no-progress --browsers=ChromeNoSandbox
      - run: xvfb-run -a npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
